version: '2'
services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_development
  web:
    image: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - db:db
    ports:
        - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: web_development
      DB_HOST: db
